project:
  type: website
  output-dir: docs

website:
  title: "Brett Johnson's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Br-Johnson 
      - icon: twitter
        href: https://twitter.com/_BrettJohnson
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

